#pragma config(Motor,  motorB,          mb,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define CX	89
#define CY	19
#define RADIUS	69

task main()
{
	setMotorBrakeMode(mb, motorCoast);
	resetMotorEncoder(mb);

	float rpm;
	int dx, dy;

	while(true)
	{
		eraseDisplay();
		rpm = getMotorRPM(mb);
		displayCenteredBigTextLine(1, "RPM of Motor");

			dx = RADIUS * cosDegrees(180-rpm) + CX;
			dy = RADIUS * sinDegrees(rpm) + CY;

		//draw Big Circle & small circle
		drawEllipse(20, -70, 160, 90);
		drawEllipse(85, 17, 93, 27);

		//draw arrow
		drawLine(CX, CY, dx, dy);
		fillEllipse(CX, CY, dx, dy);

		displayCenteredBigTextLine(14, "%.2f", rpm);
		sleep(50);
	}

}
